#配置日志
logging:
  #配置日志文件路径 不同目录下的日志可配置不同级别
  level:
    root: info
server:
  port: 9091

AS400:
  systemName: SystemName;
  username: Username
  password: Password
  jobName: jobName
  jobNumber: jobNumber
  jobuser: jobuser
