#配置日志
logging:
  #配置日志文件路径 不同目录下的日志可配置不同级别
  level:
    root: info
server:
  port: 8080

webDriver:
  ie: src/main/resources/WebDriver/IEDriverServer.exe  #IEDriverServer_x64_3.141.59
  chrome: src/main/resources/WebDriver/chromedriver.exe  #chromedriver_win32_74.0.3729.6