#配置日志
logging:
  #配置日志文件路径 不同目录下的日志可配置不同级别
  level:
    root: INFO
server:
  port: 8080
  
#ssl
#keyStore: /servers.keystore
keyStore: /uat.keystore
passWord: 123456

#gpg
#publicKey: /pubKey.asc  
publicKey: /DBSSG_EN_PUBLIC.asc
file5: /file5.txt

#url
#url5: https://10.11.22.228:8443/getRequestInfo
url5: https://api-ideal-uat.dbs.com/rapid/hkfaster/v1/payment/initiatePayment