#配置日志
logging:
  #配置日志文件路径 不同目录下的日志可配置不同级别
  level:
    root: INFO
server:
  port: 8080
  
#ssl
Dual: 2
keyStoreFile: /testCL.p12
#keyStoreFile: /uat.keystore
keyStorePass: 123456
trustStoreFile: /testSV.keystore
trustStorePass: 123456

#gpg
#publicKey: /pubKey.asc  
publicKey: /DBSSG_EN_PUBLIC.asc
file5: /file5.txt
privateKey: /dbs_upgp_secret.asc

#url
url5: https://62.234.151.26:8443/getRequestInfo
#url5: https://api-ideal-uat.dbs.com/rapid/hkfaster/v1/payment/initiatePayment