#配置日志
logging:
  #配置日志文件路径 不同目录下的日志可配置不同级别
  level:
    root: info
server:
  port: 9090
  
#ssl
Dual: 1
keyStoreFile: D:/fps_test/testCL.p12
#keyStoreFile: /uat.keystore
keyStorePass: 123456
trustStoreFile: D:/fps_test/uat.keystore
trustStorePass: 123456

#gpg
#publicKey: /pubKey.asc  
publicKey: D:/fps_test/DBSSG_EN_PUBLIC.asc
file5: D:/fps_test/file5.txt
privateKey: D:/fps_test/dbs_upgp_secret.asc

#url https://api-ideal-uat.dbs.com/rapid/enquiry/v1/cashk/verification
#https://api-ideal-uat.dbs.com/rapid/hkfaster/v1/payment/initiatePayment
#url5: https://localhost:8443/getRequestInfo
url5: https://api-ideal-uat.dbs.com/rapid/enquiry/v1/cashk/verification